services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: devover/aksaria:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - aksaria-network

  db:
    image: postgres:17.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-aksaria}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-aksaria}"]
      interval: 10s
      timeout: 5s
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - aksaria-network

networks:
  aksaria-network:
    driver: bridge

volumes:
  db_data: